# frozen_string_literal: true
source "https://rubygems.org"

# https://www.ruby-lang.org/en/downloads/releases
ruby file: ".ruby-version"

# Jekyll Dependencies
gem "jekyll", "~> 3.10"  # 4.3
gem "jekyll-remote-theme", "~> 0.4.3"
gem "jekyll-seo-tag", "~> 2.8"

# Silence Standard Library Removal Warnings
gem "logger", "~> 1.6"
gem "csv", "~> 3.3"
gem "ostruct", "~> 0.6.1"
gem "base64", "~> 0.2.0"

# Silences Faraday Warnings from Github Pages
gem "faraday-retry", "~> 2.2"

# Allow Github Pages Jekyll Theme to Work Locally
gem "github-pages", group: :jekyll_plugins

# Jekyll Theme
# gem "jekyll-theme-midnight", "~> 0.2.0"
